Mountain/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from products.views import products, cart

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', products, name="home"),

    # url(r'^cart/$', cart, name="cart"),

    url(r'^products/', include('products.urls')),
    url(r'^docs/', include('rest_framework_docs.urls')),
    url(r'^accounts/', include('accounts.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url

# from cart.views import CartView
#
# urlpatterns = [
#
#     url(r'^(?P<cart_id>[\d]+)/cart$', CartView, name="cart"),
# ]

cart/models.py
from django.db import models

from products.models import Product


class Cart(models.Model):
    full_cart = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)


class CartItem(models.Model):
    cart = models.ForeignKey('Cart', null=True, blank=True)
    item = models.ForeignKey(Product)
    quantity = models.PositiveIntegerField(default=1)
    item_total_price = models.DecimalField(max_digits=50, decimal_places=2, null=True, blank=True)

cart/forms.py
from django import forms

from products.models import Product


# class CartForm(forms.Form):
#     products = forms.ModelChoiceField(label=u'Products', queryset=Product.objects.all())

cart/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from django.http import HttpResponse

# from cart.forms import CartForm
from cart.models import Cart, CartItem
from products.models import Product


from django.conf import settings


# def add_to_cart(request, item_id, quantity):
#     cart = request.session.get('cart', {})
#     cart[item_id] = quantity
#     request.session['cart'] = cart

# def view_cart(request):
#     session = request.session
#     cart = session.get(settings.CART_SESSION_ID)
#     if not cart:
#         cart = session[settings.CART_SESSION_ID] = {}



# def view_cart(request):
#     cart = request.session.get('cart', {})
#
#
# def add_to_cart(request, item_id, quantity):
#     cart = request.session.get('cart', {})
#     cart[item_id] = quantity
#     request.session['cart'] = cart
#
# def add(request):
#     cart = Cart(request.session)
#     product = Product.objects.get(id=request.GET.get('product_id'))
#     cart.add(product, price=product.price)
#     return HttpResponse("Added")
#
# def show(request):
#     return render(request, 'shopping/show-cart.html')



# class CartView(FormView):
#     template_name = 'cart.html'
#     form_class = CartForm
#
#     def get(self, request, *args, **kwargs):
#         cart_id = self.request.session.get("cart_id")
#         if cart_id == None:
#             cart = Cart()
#             cart.save()
#             cart_id = cart.id
#             self.request.session["cart_id"] = cart_id
#         cart = Cart.objects.get(id=cart_id)
#
#     def add_to_cart(self, request, item_id, quantity):
#         cart = request.session.get('cart', {})
#         cart[item_id] = quantity
#         request.session['cart'] = cart
#
#         if not request.is_ajax():
#             form = self.get_form()
#             return self.render_to_response(self.get_context_data(form=form, cart=cart))
#
#         if request.is_ajax():
#             item_id = request.GET.get("product")
#             item_instance = get_object_or_404(Product, id=item_id)
#             cart_item, created = CartItem.objects.get_or_create(cart=cart, item=item_instance)
#             if not created:
#                 cart_item.quantity += 1
#                 cart_item.save()
#
#             data = {}
#             return JsonResponse(data)

cart/templates/cart.html
{#{% block jquery %}#}
{##}
{#    $('.btn-default').click(function(e){#}
{#        var product = $('select option:selected').val();#}
{#        var data = {product: product};#}
{#        $.ajax({#}
{#            type: 'GET',#}
{#            url:'{% url "cart" %}',#}
{#            data: data#}
{#        });#}
{#    });#}
{##}
{#{% endblock %}#}

{#{% extends 'base.html' %}#}
{#{% block content %}#}
{##}
{#<div class="container">#}
{#    <div class="row products">#}
{#        <div class="col-md-4 col-md-offset-4">#}
{#            <form action="." method="GET">{% csrf_token %}#}
{#                {{ form|crispy }}#}
{#                {{ form }}#}
{##}
{#                <input class="btn btn-default" type="button" value="Add to cart" />#}
{#            </form>#}
{#        </div>#}
{#    </div>#}
{#<div class='row cart'>#}
{#        <div class='col-md-8 col-md-offset-2'>#}
{##}
{#            <h3>Your cart</h3>#}
{##}
{#            <table class='table'>#}
{#                <tr>#}
{#                    <th>Item</th>#}
{#                    <th>Price</th>#}
{#                    <th>Qty</th>#}
{#                    <th>Item Total</th>#}
{#                </tr>#}
{##}
{#                {% for item in cart.cartitem_set.all %}#}
{#                    <tr>#}
{#                        <td>{{ item.item.sku }}</td>#}
{#                        <td>{{ item.item.price }}</td>#}
{#                        <td>{{ item.quantity }}</td>#}
{#                        <td>{{ item.item_total_price }}</td>#}
{#                    </tr>#}
{#                {% endfor %}#}
{##}
{#                <tr id="checkout">#}
{#                    <td colspan='4' class='text-right'>Total: {{cart.total}}</td>#}
{#                </tr>#}
{#                <tr id="checkout">#}
{#                    <td colspan='4' class='text-right'><a class='btn btn-warning' href="{% url 'checkout' %}">Checkout</a></td>#}
{#                </tr>#}
{##}
{#            </table>#}
{##}
{#        </div>#}
{#    </div>#}
{#</div>#}
{##}
{#{% endblock %}#}